project:
  type: book
  output-dir: docs
  
book:
  title: "AI Assistants Maximized"
  subtitle: "Tips and Tricks for Programmers"
  author: "Sam Parmar"
  # date: "7/17/2023"
  site-url: parmsam.github.io/tips-and-tricks-ai-tools/
  repo-url: https://github.com/parmsam/tips-and-tricks-ai-tools
  sharing: [twitter, facebook]
  search: true
  chapters:
    - index.qmd
    - intro.qmd
    - learn-more.qmd
    # - references.qmd
  favicon: "images/DALL·E 2023-07-17 23.32.52 - Ukrainian dog wearing a beret and black turtleneck.png"
  sidebar:
    logo: "images/DALL·E 2023-07-17 23.32.52 - Ukrainian dog wearing a beret and black turtleneck.png"

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-copy: true

code-copy: true

