project:
  type: book
  output-dir: docs
  
book:
  title: "AI Assistants Maximized"
  subtitle: "Tips and Tricks for Programmers"
  author: "Sam Parmar"
  reader-mode: false
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>
  site-url: parmsam.github.io/tips-and-tricks-ai-tools/
  repo-url: https://github.com/parmsam/tips-and-tricks-ai-tools
  repo-branch: master
  repo-actions: [edit, issue]
  sharing: [twitter, facebook]
  search: true
  page-navigation: true
  chapters:
    - index.qmd
    - intro.qmd
    - uses.qmd
    - considerations.qmd
    - workflow.qmd
    - learn-more.qmd
  appendices:
    - shiny.qmd
    # - references.qmd
  favicon: "images/DALL·E 2023-07-17 23.32.52 - Ukrainian dog wearing a beret and black turtleneck.png"
  sidebar:
    logo: "images/DALL·E 2023-07-17 23.32.52 - Ukrainian dog wearing a beret and black turtleneck.png"

bibliography: references.bib

format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    code-link: true
    code-copy: true
    code-overflow: wrap
