# Intro

This chapter provides an overview of commonly used AI assistance tools that are revolutionizing various areas, from software development to creative writing and beyond.

## ChatGPT

[ChatGPT](https://chat.openai.com/) is a large language model chatbot developed by OpenAI. It can be used for a multitude of tasks, such as:

- Following instructions and completing requests
- Answering questions in an informative way, even if they are open-ended, challenging, or strange
- Generating different creative text formats like poems, code, scripts, emails, or letters

You can augment ChatGPT via [various plugins](https://openai.com/blog/chatgpt-plugins), which extend its capabilities to specialized tasks like coding assistance, real-time translation, and more.

As of 2023, ChatGPT has seen improvements in its conversational depth, allowing for more nuanced and context-aware responses. It has also expanded its range of plugins and added [custom instructions](https://openai.com/blog/custom-instructions-for-chatgpt), offering even more specialized functionalities (see be specific section of the considerations chapter for more on this). For example, in Sept 2023, OpenAI announced [prompting with voice and images](https://openai.com/blog/chatgpt-can-now-see-hear-and-speak) and [DALL-E 3 integration](https://www.theverge.com/2023/9/20/23881241/openai-dalle-third-version-generative-ai) for ChatGPT.

## DALLE 2

[DALLE 2](https://openai.com/dall-e-2) is a text-to-image diffusion model developed by OpenAI. It can be used to create realistic images from text descriptions. DALLE 2 has been shown to be able to create high-quality images of a variety of objects and scenes.

## Bard

[Bard](https://bard.google.com/) is a large language model chatbot developed by Google AI. It is a powerful tool that can be used for a variety of tasks, including generating text, translating languages, and writing different kinds of creative content. It was developed by Google as a direct response to ChatGPT.

## Github Copilot

[Github Copilot](https://github.com/features/copilot) is a code completion tool developed by GitHub and OpenAI. It uses a large language model to suggest code completions via [ghost text](https://code.visualstudio.com/blogs/2023/03/30/vscode-copilot) as a user types. GitHub Copilot has also been shown to be able to suggest accurate and relevant code completions for a variety of programming languages. It works with code editors such as [VSCode](https://en.wikipedia.org/wiki/Visual_Studio_Code) and [Jetbrains IDEs](https://en.wikipedia.org/wiki/JetBrains).

A [Github Copilot Chat](https://docs.github.com/en/copilot/github-copilot-chat/using-github-copilot-chat) integration is also supported via a VSCode extension.

## Summary

These are just a few of the many AI assistance tools that are available. As AI technology continues to develop, we can expect to see even more powerful and sophisticated tools that can help developers with a variety of tasks.
