# Learn more

Check out these resources to dive deeper into the tools and tricks covered in this guide.

## Using Github Copilot

- [How to use GitHub Copilot: Prompts, tips, and use cases](https://github.blog/2023-06-20-how-to-write-better-prompts-for-github-copilot/)

- [How to Use GitHub Copilot to Become a Happier and More Productive Developer](https://www.freecodecamp.org/news/developer-productivity-with-github-copilot/)

- [How to use GitHub Copilot: Prompts, tips, and use cases](https://github.blog/2023-06-20-how-to-write-better-prompts-for-github-copilot/)

- [Getting started with GitHub Copilot](https://docs.github.com/en/copilot/getting-started-with-github-copilot)

## Using DALL-E 2

- [How to use DALL·E 2 to create AI images](https://zapier.com/blog/how-to-use-dall-e-2/)

## Prompt engineering

- [Prompt Engineering Guide](https://www.promptingguide.ai/)

- [Six tips for better coding with ChatGPT](https://www.nature.com/articles/d41586-023-01833-0)

- [How to write an effective GPT-3 or GPT-4 prompt](https://zapier.com/blog/gpt-prompt/)

- [ChatGPT Guide: Use these prompt strategies to maximize your results](https://the-decoder.com/chatgpt-guide-prompt-strategies/)

- [Hamel's notebooks from the deeplearning.ai course on Prompt Engineering](https://hamel.dev/notes/prompt-eng/course/)

- [OpenAI Cookbook](https://github.com/openai/openai-cookbook)

- [GPT Best Practices from OpenAI](https://platform.openai.com/docs/guides/gpt-best-practices)

### Videos

- [Prompt Engineering Tutorial – Master ChatGPT and LLM Responses](https://www.youtube.com/watch?v=_ZvnD73m40o)

- [Andrew Ng: Opportunities in AI - 2023](https://www.youtube.com/watch?v=5p248yoa3oE)

### Simon Willison's talks on LLMs

- [Catching up on the weird world of LLMs](https://simonwillison.net/2023/Aug/3/weird-world-of-llms/)

- [Making Large Language Models work for you](https://simonwillison.net/2023/Aug/27/wordcamp-llms/)

## How ChatGPT works

- [What Is ChatGPT Doing … and Why Does It Work?](https://writings.stephenwolfram.com/2023/02/what-is-chatgpt-doing-and-why-does-it-work/)

- [What are Large Language Models? What are they not?](https://blogs.rstudio.com/ai/posts/2023-06-20-llm-intro/)
